[package]
authors = ["Maxwell Rupp <gignsky@gignsky.com>"]
# If you change the name here, you must also do it in flake.nix (and run `cargo generate-lockfile` afterwards)
name = "gignsky-dot-com"
description = "A simple Rust project using Nix"
version = "0.0.0"
edition = "2024"

[dependencies]
